# Generated by Django 2.2 on 2020-09-30 11:21

import cropperjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', cropperjs.models.CropperImageField(aspectratio='1.0', blank=True, dimensions=(1750, 1750), upload_to='item_images', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
